apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: student-attendance

  labels:
    app: backend

spec:
  replicas: 1

  revisionHistoryLimit: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: 962415228964.dkr.ecr.ap-south-1.amazonaws.com/student-attendance-dev-application:backend-v1
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: attendance-config
            - secretRef:
                name: attendance-secret

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "200m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3