apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: student-attendance

  labels:
    app: frontend

spec:
  replicas: 1

  revisionHistoryLimit: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: 962415228964.dkr.ecr.ap-south-1.amazonaws.com/student-attendance-dev-application:frontend-v1
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"

            limits:
              cpu: "100m"
              memory: "128Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3