apiVersion: v1
kind: ConfigMap

metadata:
  name: attendance-config
  namespace: student-attendance

data:
  SPRING_PROFILES_ACTIVE: "dev"

  DB_HOST: "student-attendance-dev-postgres.cp0skiccktil.ap-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "attendance_db"

  AWS_REGION: "ap-south-1"

  PORT: "3000"